name: diario_de_bordo

environment:
  sdk: ^3.8.0-0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

  webdriver: any

# PUBSPEC CHECKSUM: mut18q
